#!/bin/bash

source /usr/share/yunohost/helpers

upstream_version=$(ynh_app_upstream_version)
index_page="CyberChef_v${upstream_version}.html" #this variable will also populate the template tag __INDEX_PAGE__ in nginx.conf

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
